//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CancelMessage
    {
        public int MessageId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Message { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual User User { get; set; }
    }
}
